apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ats.cnat.programming-kubernetes.info
spec:
  group: cnat.programming-kubernetes.info
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: At
    plural: ats
  scope: Namespaced
