apiVersion: cnat.programming-kubernetes.info/v1alpha1
kind: At
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: example2-at
spec:
  schedule: "2021-05-21T03:52:00Z"
  command: "echo Toronto!"
